=== ffblk/epam/Cinema/App_Data/repertory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="repertory">
    <xsd:complexType>
      <xsd:sequence>
  <xsd:element name="cinema" maxOccurs="unbounded">
    <xsd:complexType>
      <xsd:sequence>
      <xsd:element name ="id" type="xsd:integer"/>
      <xsd:element name ="name" type="xsd:string"/>
      <xsd:element name ="description" type="xsd:string"/>
      <xsd:element name ="link" type="Link"/> 
        </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="Link">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\w+\.((png)|(jpg))" />
    </xsd:restriction>
  </xsd:simpleType>
  
</xsd:schema>

=== ffblk/epam/Cinema/App_Data/repertory.xml
<?xml version="1.0" encoding="utf-8" ?>
<repertory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="repertory.xsd">
  <cinema>
    <id>1</id>
    <name>Терминатор</name>
    <description>
	История противостояния солдата Кайла Риза и киборга-терминатора, прибывших в 1984-й год из пост-апокалиптического будущего, где миром правят машины-убийцы, а человечество находится на грани вымирания. Цель киборга: убить девушку по имени Сара Коннор, чей ещё нерождённый сын к 2029 году выиграет войну человечества с машинами. Цель Риза: спасти Сару и остановить Терминатора любой ценой.
	</description>  
    <link>terminator.jpg</link>
  </cinema>
  <cinema>
    <id>2</id>
    <name>Побег из Шоушенка</name>
    <description>
	Успешный банкир Энди Дюфрейн обвинен в убийстве собственной жены и ее любовника. Оказавшись в тюрьме под названием Шоушенк, он сталкивается с жестокостью и беззаконием, царящими по обе стороны решетки. Каждый, кто попадает в эти стены, становится их рабом до конца жизни. Но Энди, вооруженный живым умом и доброй душой, отказывается мириться с приговором судьбы и начинает разрабатывать невероятно дерзкий план своего освобождения.
	</description>
    <link>pobeg.jpg</link>
  </cinema>
  <cinema>
    <id>3</id>
    <name>Аватар</name>
    <description>
	Джейк Салли — бывший морской пехотинец, прикованный к инвалидному креслу. Несмотря на немощное тело, Джейк в душе по-прежнему остается воином. Он получает задание совершить путешествие в несколько световых лет к базе землян на планете Пандора, где корпорации добывают редкий минерал, имеющий огромное значение для выхода Земли из энергетического кризиса.
	</description>
    <link>avatar.jpg</link>
  </cinema>
</repertory>
